### ISSUE TITLE
Cannot resolve com.amazonaws.auth.profile

### ISSUE THREAD

**Issue by shivarajp** [awslabs/aws-sdk-android-samples#102]
Hi, I'm trying to use AWS rekognition java [sample](http://docs.aws.amazon.com/rekognition/latest/dg/example2.html) in my android app but it cannot identify new ProfileCredentialsProvider("adminuser").getCredentials();
 and .withEndpoint("service endpoint"); in AmazonRekognitionClient(credentials). .withEndpoint("service endpoint");

I'm using compile 'com.amazonaws:aws-android-sdk-core:2.3.9'
aws-android-sdk-rekognition-2.3.9.jar 

It would be great if you can upload a working android sample for AWS rekognition.

**Comment by minbi** [comment]
Hi @shivarajp,

It looks like you are trying to use the Java SDK instead of the Android SDK.
Please see docs for [Getting Credentials](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html).
The options for creating a [CognitoCachingCredentialsProvider](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java#L184).
And options for creating a [AmazonRekognitionClient](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-rekognition/src/main/java/com/amazonaws/services/rekognition/AmazonRekognitionClient.java#L116)

**Comment by minbi** [comment]
Please re-open if you have more information or questions
