### ISSUE TITLE
Request - Add example of accessing Lambda function protected by Cognito Federated Identities

### ISSUE THREAD

**Issue by vyscond** [awslabs/aws-sdk-android-samples#175]
Hello,

Currently i'm reading the `CognitoSyncDemo` example and trying to apply that to access my Lambda function that was code using the `chalice` framework. But it's kind confusing to me and i still taking a lot of time to understand the data workflow presented on the AWS Cognito documentation pages on the code itself.

Plus one thing is that this `CognitoSyncDemo` focus too much on third party services like facebook to get the OAuth2 tokens. Why not getting an exclusive example of using the Cognito Identities Pools as the main provider of the OAuth2?

Besides that, the other example are more easy to read (less steps to follow) but all of them have a lot of good documentation. Thanks for the good work :)

**Comment by muellerfr** [comment]
Hello @vyscond,

Please use [AWS AppSync](https://aws.amazon.com/appsync/resources/) instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
