### ISSUE TITLE
About policy consistency

### ISSUE THREAD

**Issue by JoonDong2** [awslabs/aws-sdk-android-samples#188]
I attempted to connect, get shadow by using authenticated Cognito identity. 

My policy(in IAM) attached to role authenticated Cognito identity assume is below.

    iot:Connect
    iot:AttachPrincipalPolicy
    iot:DetachPirncipalPolicy
    iot:Publish
    iot:Subscribe
    iot:Receive
    iot:GetThingShadow

Connect, AttachPrincipalPolicy, DetachPrincipalPolicy, Publish and Subscribe work well, although I did not attach any policy in IoT service (in this [link](https://forums.aws.amazon.com/thread.jspa?messageID=699362), it is mentioned that Cognito identities need to be granted additional permissions in IoT).

But when I attempted to get thing's shadow using AWSIotDataClient instance, it threw ForbiddenException. To solve this problem, I tried to attach a policy allowing GetThingSadow in IoT service using AWSIotClient instance(although it exist in IAM policy already), so it works well.

The question here is that whether there are actions that require additional privileges in IoT service or not when I use Cognito identity and associated role in IAM(i.e. using STS).

**Comment by cbommas** [comment]
Hello @JoonDong2 

Please look at https://forums.aws.amazon.com/thread.jspa?messageID=699362 for answers to your question.

As per AlexS@AWS on that thread, 

"_All authenticated Cognito identities need to be granted additional permissions in IoT for data plane operations (publish, subscribe, etc., plus device shadow operations). To do that you need to create a policy in IoT and then attach it to the identity using AttachPrincipalPolicy. This is in addition to the permissions on the pool as the final permission for the identity is the intersection of the permissions granted by the two policies. IAM users do not need an additional policy in IoT which is why it works for your IAM users but not for Cognito identities. For more details see http://docs.aws.amazon.com/iot/latest/developerguide/authorization.html#pub-sub-policy-cognito.

Note that this does not apply for unauthenticated Cognito identities. An unauthenticated Cognito identity gets its permissions only from the permissions attached to the unauthenticated Cognito pool._"
