### ISSUE TITLE
Using Unauthenticated Identity Pool Id for Kinesis Video Stream

### ISSUE THREAD

**Issue by gerahimanshu** [awslabs/aws-sdk-android-samples#243]
In my application, i don't want the user to be logged in, therefore using unauthenticated identity pool id. But when i am using the identity into my code, it gives me the following error:

```
EXCEPTION: AmazonServiceException: Service call failed.: User: arn:aws:sts::xxxx:assumed-role/Cognito_camera_control_poolUnauth2_Role/CognitoIdentityCredentials is not authorized to perform: kinesisvideo:DescribeStream (Service: AWSKinesisVideo; Status Code: 403; Error Code: AccessDeniedException; Request ID: d62bf3c1-57ac-1b02-85de-6e9542fec450)
```

Please help!

**Comment by kvasukib** [comment]
@gerahimanshu Have you attached the policy with "kinesisvideo:DescribeStream" permission to the Unauthenticated role of your Cognito Identity pool?

**Comment by gerahimanshu** [comment]
I have attached the policy as "kinesisvideo:*"

**Comment by kvasukib** [comment]
@gerahimanshu Thank you for the reply. Can you try to create the CognitoCachingCredentialsProvier using this [constructor](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java#L121)? You need to fetch the ARN of the roles from the Cognito and IAM console in order to use this constructor?

**Comment by gerahimanshu** [comment]
Thanks a ton! It worked like a charm :)

**Comment by kvasukib** [comment]
Thank you @gerahimanshu for the reply. I will convey this bug to the team to add support for the other Cognito constructor that you were using with Kinesis Video.
