### ISSUE TITLE
Signature in CognitoSyncDemo

### ISSUE THREAD

**Issue by angelromero** [awslabs/aws-sdk-android-samples#28]
Hi
I have a question, the Android client sends the timestamp to the login endpoint.
the login endpoint validates if the result of signing that timestamp with the user's salted password from the DB matches the signature sent by the android client.
Is that correct? because timestamps are different between the one used when storing the user and the one sent by the client android, signatures will never match.
Is the validateSignature in login correct, am I missing a concept?
I'm talking about the developer authentication mode.
Thanks
Angel

**Comment by turacma** [comment]
Angel:

Yes, as part of the login request, the timestamp of the request is signed. On the server, the [signature is verified](https://github.com/awslabs/amazon-cognito-developer-authentication-sample/blob/72d7e9ff29296d408dfdb0891ff2bdab6344a505/src/main/java/com/amazonaws/cognito/devauthsample/identity/AWSCognitoDeveloperAuthenticationSample.java#L192) based on the value of timestamp passed in, it is not the timestamp of the time the request was received nor the timestamp of when the user was created.

In order to minimize the possibility of a replay attack, the server allows a [timestamp difference of up to 15 minutes](https://github.com/awslabs/amazon-cognito-developer-authentication-sample/blob/master/src/main/java/com/amazonaws/cognito/devauthsample/Utilities.java#L104).
