### ISSUE TITLE
Pause/Resume function

### ISSUE THREAD

**Issue by catalinclabescu** [awslabs/aws-sdk-android-samples#48]
While running the sample available here I have encountered some issues regarding the Pause/Resume functionality. First of all, in the documentation it is stated that if a transfer is interrupted by network connectivity loss, upon reconnection the transfer will be automatically resumed. However, this is not the case, as the transfer enters FAILED state when connectivity is lost, and doesn't resume automatically. Second, I have tried uploading a large file (~27 MB), paused the transfer at 18 MB, but when I have pressed the Resume button, the transfer was restarted from the beginning. Only if paused near the end (more than 22MB) does the transfer resume from around 7MB. Before the upload began, I saw the following line in the logs:

03-31 16:44:35.800 32183-424/com.amazonaws.demo.s3transferutility D/UploadTask: multipart upload 98 in 6 parts.

So I would have expected that, for example, if I pause the transfer after 10MB were uploaded, the transfer would be resumed from 8MB.

How can I properly set up a multipart transfer using the TransferUtility and what are the limitations regarding minimum file size and part size?

**Comment by fosterzhang** [comment]
Two questions here:
- Why does TransferUtility not resume on network loss? The way TransferUtility detects network is via broadcast receiver. If TransferUtility is informed by the system about network status change, it'll pause current transfers and will resume when the network comes back. However there are cases where the system isn't aware of a network connectivity issue and doesn't notify TransferUtility. One example is that your phone is on Wifi via a router, but the router loses LAN connection.
- Why does TransferUtility not resume at where it was? This is due to the limitation of S3. The minimum part size in multipart upload is 5mb. A part has to be fully uploaded or it'll be discarded. Say you upload a 30mb file, in 6 parts, and 2-4 uploads (based on # of cores) will occur in parallel. If one is done, and three others are at 4mb, you will see transfer progress at 5 + 4*3 = 17. If you pause it, the three incomplete parts will be discarded and the transfer will be resumed at 5mb.
