### ISSUE TITLE
 com.amazonaws.mobileconnectors.cognito.exceptions.DataStorageException

### ISSUE THREAD

**Issue by techvedikasolutions** [awslabs/aws-sdk-android-samples#95]
client.refreshDatasetMetadata();

getting the above error while executing the above line , what could be the issue for this , please help me out ,

**Comment by karthiksaligrama** [comment]
what version of the sdk are you using? Can you also mention whats the android version?

**Comment by jbailey2010** [comment]
Do you have the message that the error is throwing?

**Comment by muellerfr** [comment]
Hello @techvedikasolutions,

Please use [AWS AppSync](https://aws.amazon.com/appsync/resources/) instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
